<?php

namespace Database\Seeders;

use App\Models\Admin\Rubric\Rubric;
use Illuminate\Database\Seeder;

class RubricSeeder extends Seeder
{
    /**
     * Запуск сидера.
     */
    public function run(): void
    {
        $defaultIcon = '<svg class="w-4 h-4 fill-current text-slate-400 shrink-0 mr-3" viewBox="0 0 16 16"><path d="M15 15V5l-5-5H2c-.6 0-1 .4-1 1v14c0 .6 0 1 1 1h12c.6 0 1-.4 1-1zM3 2h6v4h4v8H3V2z"></path></svg>';

        $rubrics = [
            [
                'sort' => 1,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Новости',
                'url' => 'novosti',
                'short' => 'Новости профессионального бокса',
                'description' => 'Свежие новости профессионального бокса: актуальные события, интервью, аналитика и результаты боёв. Следите за последними тенденциями в мире бокса',
                'views' => '0',
                'meta_title' => 'Новости профессионального бокса',
                'meta_keywords' => 'бокс, профессиональный бокс, новости бокса, интервью с боксёрами, аналитика боёв, результаты боёв, казахстанский бокс, мировые боксёрские события',
                'meta_desc' => 'Свежие новости профессионального бокса: актуальные события, интервью, аналитика и результаты боёв. Следите за последними тенденциями в мире бокса',
            ],
            [
                'sort' => 2,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Расписание',
                'url' => 'raspisanie',
                'short' => 'Рейтинги боксёров по весовым категориям',
                'description' => 'Актуальные рейтинги профессиональных боксёров по весовым категориям: следите за позициями казахстанских и мировых спортсменов, обновлениями и аналитикой',
                'views' => '0',
                'meta_title' => 'Рейтинги боксёров по весовым категориям',
                'meta_keywords' => 'рейтинги бокса, профессиональный бокс, рейтинги боксёров, весовые категории, казахстанский бокс, мировые боксёрские рейтинги, P4P',
                'meta_desc' => 'Актуальные рейтинги профессиональных боксёров по весовым категориям: следите за позициями казахстанских и мировых спортсменов, обновлениями и аналитикой',
            ],
            [
                'sort' => 3,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Интервью',
                'url' => 'intervyu',
                'short' => 'Интервью с профессиональными боксёрами',
                'description' => 'Эксклюзивные интервью с казахстанскими и мировыми профессиональными боксёрами: мнения, стратегии, подготовка к боям и личные истории. Узнайте больше',
                'views' => '0',
                'meta_title' => 'Интервью с профессиональными боксёрами',
                'meta_keywords' => 'интервью боксёров, профессиональный бокс, казахстанские боксёры, мировые боксёры, мнения спортсменов, подготовка к боям, личные истории боксёров',
                'meta_desc' => 'Эксклюзивные интервью с казахстанскими и мировыми профессиональными боксёрами: мнения, стратегии, подготовка к боям и личные истории. Узнайте больше',
            ],
            [
                'sort' => 4,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Обзоры',
                'url' => 'obzory',
                'short' => 'Прогнозы и обзоры бокса — Аналитика боёв',
                'description' => 'Актуальные прогнозы и аналитические обзоры профессиональных боксёрских поединков. Оценка предстоящих боёв, разбор тактик, мнения экспертов и подробности о казахстанских и мировых боксерах',
                'views' => '0',
                'meta_title' => 'Прогнозы и обзоры бокса — Аналитика боёв',
                'meta_keywords' => 'прогнозы боёв, обзоры бокса, аналитика бокса, профессиональный бокс, казахстанский бокс, мировые боксёрские события, тактика боёв',
                'meta_desc' => 'Актуальные прогнозы и аналитические обзоры профессиональных боксёрских поединков. Оценка предстоящих боёв, разбор тактик, мнения экспертов и подробности о казахстанских и мировых боксерах',
            ],
            [
                'sort' => 5,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Результаты',
                'url' => 'rezultaty',
                'short' => 'Результаты профессиональных боксёрских боёв',
                'description' => 'Актуальные результаты завершённых боксёрских поединков: победы, поражения, нокауты и судейские решения. Следите за итогами боёв казахстанских и мировых боксёров',
                'views' => '0',
                'meta_title' => 'Результаты профессиональных боксёрских боёв',
                'meta_keywords' => 'результаты боёв, профессиональный бокс, итоги поединков, нокауты, судейские решения, казахстанский бокс, мировые боксёрские результаты',
                'meta_desc' => 'Актуальные результаты завершённых боксёрских поединков: победы, поражения, нокауты и судейские решения. Следите за итогами боёв казахстанских и мировых боксёров',
            ],
            [
                'sort' => 6,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Open Ring',
                'url' => 'open-ring-ru',
                'short' => 'Открытый ринг — Мнения и дискуссии о боксе',
                'description' => 'Раздел "Открытый ринг" — это платформа для обсуждения актуальных тем в мире профессионального бокса. Читайте мнения экспертов, делитесь своими взглядами и участвуйте в дискуссиях о казахстанском и мировом боксе.',
                'views' => '0',
                'meta_title' => 'Открытый ринг — Мнения и дискуссии о боксе',
                'meta_keywords' => 'открытый ринг, обсуждение бокса, мнения о боксе, дискуссии о боксе, профессиональный бокс, казахстанский бокс, мировые боксёрские события',
                'meta_desc' => 'Раздел "Открытый ринг" — это платформа для обсуждения актуальных тем в мире профессионального бокса. Читайте мнения экспертов, делитесь своими взглядами и участвуйте в дискуссиях о казахстанском и мировом боксе.',
            ],
            [
                'sort' => 7,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'WBSS',
                'url' => 'wbss-ru',
                'short' => 'World Boxing Super Series (WBSS) — Новости и обзоры турнира',
                'description' => 'Следите за последними новостями, результатами и аналитикой турнира World Boxing Super Series (WBSS). Узнайте о победителях, участниках и ключевых моментах турнира, включая обладателей трофея Мухаммеда Али',
                'views' => '0',
                'meta_title' => 'World Boxing Super Series (WBSS) — Новости и обзоры турнира',
                'meta_keywords' => 'WBSS, World Boxing Super Series, трофей Мухаммеда Али, результаты WBSS, участники WBSS, профессиональный бокс, турниры по боксу',
                'meta_desc' => 'Следите за последними новостями, результатами и аналитикой турнира World Boxing Super Series (WBSS). Узнайте о победителях, участниках и ключевых моментах турнира, включая обладателей трофея Мухаммеда Али',
            ],
            [
                'sort' => 8,
                'activity' => 0,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Новости DIAMONDRING',
                'url' => 'novosti-diamondring',
                'short' => 'Новости DIAMONDRING',
                'description' => 'Новости DIAMONDRING',
                'views' => '0',
                'meta_title' => 'Новости DIAMONDRING',
                'meta_keywords' => 'Новости, DIAMONDRING',
                'meta_desc' => 'Новости DIAMONDRING',
            ],
            [
                'sort' => 9,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Рейтинг Р4Р',
                'url' => 'reyting-r4r',
                'short' => 'Рейтинг лучших боксёров вне зависимости от весовой категории (R4R)',
                'description' => 'Актуальный рейтинг лучших профессиональных боксёров вне зависимости от весовой категории (R4R). Следите за позициями казахстанских и мировых звёзд ринга, обновлениями и аналитикой',
                'views' => '0',
                'meta_title' => 'Рейтинг лучших боксёров вне зависимости от весовой категории (R4R)',
                'meta_keywords' => 'R4R, рейтинг боксёров, лучшие боксёры мира, pound for pound, профессиональный бокс, казахстанский бокс, мировые боксёрские рейтинги',
                'meta_desc' => 'Актуальный рейтинг лучших профессиональных боксёров вне зависимости от весовой категории (R4R). Следите за позициями казахстанских и мировых звёзд ринга, обновлениями и аналитикой',
            ],
            [
                'sort' => 10,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Видео',
                'url' => 'video-ru',
                'short' => 'Видео о профессиональном боксе — Бои, интервью и обзоры',
                'description' => 'Смотрите лучшие видеоматериалы о профессиональном боксе: записи боёв, интервью с казахстанскими и мировыми боксёрами, аналитические обзоры и эксклюзивные репортажи. Будьте в курсе всех событий ринга',
                'views' => '0',
                'meta_title' => 'Видео о профессиональном боксе — Бои, интервью и обзоры',
                'meta_keywords' => 'видео бокс, профессиональный бокс видео, бои боксёров, интервью боксёров, обзоры боёв, казахстанский бокс, мировые боксёрские события',
                'meta_desc' => 'Смотрите лучшие видеоматериалы о профессиональном боксе: записи боёв, интервью с казахстанскими и мировыми боксёрами, аналитические обзоры и эксклюзивные репортажи. Будьте в курсе всех событий ринга',
            ],
            [
                'sort' => 11,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Жаңалықтар',
                'url' => 'zhangalyqtar',
                'short' => 'Кәсіби бокс жаңалықтары',
                'description' => 'Кәсіби бокстың соңғы жаңалықтары: өзекті оқиғалар, сұхбаттар, аналитика және жекпе-жек нәтижелері. Бокс әлеміндегі соңғы трендтерді қадағалаңыз',
                'views' => '0',
                'meta_title' => 'Кәсіби бокс жаңалықтары',
                'meta_keywords' => 'бокс, кәсіби бокс, бокс жаңалықтары, боксшылармен сұхбат, жекпе-жек аналитикасы, жекпе-жек нәтижелері, қазақстандық бокс, әлемдік бокс оқиғалары',
                'meta_desc' => 'Кәсіби бокстың соңғы жаңалықтары: өзекті оқиғалар, сұхбаттар, аналитика және жекпе-жек нәтижелері. Бокс әлеміндегі соңғы трендтерді қадағалаңыз',
            ],
            [
                'sort' => 12,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Жаднама',
                'url' => 'zhadnama',
                'short' => 'Салмақ дәрежесі бойынша боксшылардың рейтингі',
                'description' => 'Кәсіби боксшылардың салмақ категориялары бойынша өзекті рейтингтері: қазақстандық және әлемдік спортшылардың позицияларын, жаңартулар мен талдауларды қадағалаңыз',
                'views' => '0',
                'meta_title' => 'Салмақ дәрежесі бойынша боксшылардың рейтингі',
                'meta_keywords' => 'бокс рейтингтері, кәсіби бокс, боксшылардың рейтингтері, салмақ категориялары, қазақстандық бокс, әлемдік бокс рейтингтері, P4P',
                'meta_desc' => 'Кәсіби боксшылардың салмақ категориялары бойынша өзекті рейтингтері: қазақстандық және әлемдік спортшылардың позицияларын, жаңартулар мен талдауларды қадағалаңыз',
            ],
            [
                'sort' => 13,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Сұхбат',
                'url' => 'sukhbat',
                'short' => 'Кәсіби боксшылармен сұхбат',
                'description' => 'Қазақстандық және әлемдік кәсіби боксшылармен Эксклюзивті сұхбаттар: пікірлер, стратегиялар, жекпе-жекке дайындық және жеке тарих. Көбірек біліңіз',
                'views' => '0',
                'meta_title' => 'Кәсіби боксшылармен сұхбат',
                'meta_keywords' => 'боксшылардың сұхбаттары, кәсіби бокс, қазақстандық боксшылар, әлемдік боксшылар, спортшылардың пікірлері, жекпе-жекке дайындық, боксшылардың жеке әңгімелері',
                'meta_desc' => 'Қазақстандық және әлемдік кәсіби боксшылармен Эксклюзивті сұхбаттар: пікірлер, стратегиялар, жекпе-жекке дайындық және жеке тарих. Көбірек біліңіз',
            ],
            [
                'sort' => 14,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Шолу',
                'url' => 'sholu',
                'short' => 'Бокстың болжамдары мен шолулары — Жекпе-жек аналитикасы',
                'description' => 'Кәсіби бокс матчтарының нақты болжамдары мен аналитикалық шолулары. Алдағы жекпе-жектерді бағалау, тактиканы талдау, сарапшылардың пікірлері және қазақстандық және әлемдік боксшылар туралы мәліметтер',
                'views' => '0',
                'meta_title' => 'Бокстың болжамдары мен шолулары — Жекпе-жек аналитикасы',
                'meta_keywords' => 'жекпе-жек болжамдары, бокс шолулары, бокс талдауы, кәсіби бокс, қазақстандық бокс, әлемдік бокс оқиғалары, жекпе-жек тактикасы',
                'meta_desc' => 'Кәсіби бокс матчтарының нақты болжамдары мен аналитикалық шолулары. Алдағы жекпе-жектерді бағалау, тактиканы талдау, сарапшылардың пікірлері және қазақстандық және әлемдік боксшылар туралы мәліметтер',
            ],
            [
                'sort' => 15,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Нәтижелер',
                'url' => 'natizheler',
                'short' => 'Кәсіби бокс жекпе-жегінің нәтижелері',
                'description' => 'Аяқталған бокс матчтарының өзекті нәтижелері: жеңістер, жеңілістер, нокауттар және төрешілер шешімдері. Қазақстандық және әлемдік боксшылардың жекпе жектерінің қорытындыларын қадағалаңыз',
                'views' => '0',
                'meta_title' => 'Кәсіби бокс жекпе-жегінің нәтижелері',
                'meta_keywords' => 'жекпе-жек нәтижелері, кәсіби бокс, жекпе-жек қорытындылары, нокауттар, төрешілер шешімдері, қазақстандық бокс, әлемдік бокс нәтижелері',
                'meta_desc' => 'Аяқталған бокс матчтарының өзекті нәтижелері: жеңістер, жеңілістер, нокауттар және төрешілер шешімдері. Қазақстандық және әлемдік боксшылардың жекпе жектерінің қорытындыларын қадағалаңыз',
            ],
            [
                'sort' => 16,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Open Ring',
                'url' => 'open-ring-kk',
                'short' => 'Ашық ринг-бокс туралы пікірлер мен пікірталастар',
                'description' => '"Ашық ринг" бөлімі-бұл кәсіби бокс әлеміндегі өзекті тақырыптарды талқылауға арналған алаң. Сарапшылардың пікірлерін оқып, өз ойларыңызбен бөлісіңіз және қазақстандық және әлемдік бокс туралы пікірталастарға қатысыңыз.',
                'views' => '0',
                'meta_title' => 'Ашық ринг-бокс туралы пікірлер мен пікірталастар',
                'meta_keywords' => 'ашық ринг, боксты талқылау, бокс туралы пікірлер, бокс туралы пікірталастар, кәсіби бокс, қазақстандық бокс, әлемдік бокс оқиғалары',
                'meta_desc' => '"Ашық ринг" бөлімі-бұл кәсіби бокс әлеміндегі өзекті тақырыптарды талқылауға арналған алаң. Сарапшылардың пікірлерін оқып, өз ойларыңызбен бөлісіңіз және қазақстандық және әлемдік бокс туралы пікірталастарға қатысыңыз.',
            ],
            [
                'sort' => 17,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'WBSS',
                'url' => 'wbss-kk',
                'short' => 'World Boxing Super Series (WBSS) — турнир жаңалықтары мен шолулары',
                'description' => 'World Boxing Super Series (WBSS) турнирінің соңғы жаңалықтарын, нәтижелерін және талдауларын қадағалаңыз. Турнирдің жеңімпаздары, қатысушылары және маңызды сәттері, соның ішінде Мұхаммед Әли трофейінің иегерлері туралы біліңіз',
                'views' => '0',
                'meta_title' => 'World Boxing Super Series (WBSS) — турнир жаңалықтары мен шолулары',
                'meta_keywords' => 'WBSS, World Boxing Super Series, Мұхаммед Әли кубогы, wbss нәтижелері, wbss мүшелері, кәсіби бокс, бокстан турнирлер',
                'meta_desc' => 'World Boxing Super Series (WBSS) турнирінің соңғы жаңалықтарын, нәтижелерін және талдауларын қадағалаңыз. Турнирдің жеңімпаздары, қатысушылары және маңызды сәттері, соның ішінде Мұхаммед Әли трофейінің иегерлері туралы біліңіз',
            ],
            [
                'sort' => 18,
                'activity' => 0,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Жаңалықтар DIAMONDRING',
                'url' => 'zhangalyqtar-diamondring',
                'short' => 'Жаңалықтар DIAMONDRING',
                'description' => 'Жаңалықтар DIAMONDRING',
                'views' => '0',
                'meta_title' => 'Жаңалықтар DIAMONDRING',
                'meta_keywords' => 'Жаңалықтар, DIAMONDRING',
                'meta_desc' => 'Жаңалықтар DIAMONDRING',
            ],
            [
                'sort' => 19,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Р4Р рейтингі',
                'url' => 'r4r-reytingi',
                'short' => 'Салмақ дәрежесіне қарамастан үздік боксшылардың рейтингі (R4R)',
                'description' => 'Салмақ дәрежесіне қарамастан (R4R) үздік кәсіби боксшылардың өзекті рейтингі. Қазақстандық және әлемдік ринг жұлдыздарының позицияларын, жаңартулар мен талдауларды қадағалаңыз',
                'views' => '0',
                'meta_title' => 'Салмақ дәрежесіне қарамастан үздік боксшылардың рейтингі (R4R)',
                'meta_keywords' => 'R4R, боксшылардың рейтингі, әлемнің үздік боксшылары, pound for pound, кәсіби бокс, қазақстандық бокс, әлемдік бокс рейтингтері',
                'meta_desc' => 'Салмақ дәрежесіне қарамастан (R4R) үздік кәсіби боксшылардың өзекті рейтингі. Қазақстандық және әлемдік ринг жұлдыздарының позицияларын, жаңартулар мен талдауларды қадағалаңыз',
            ],
            [
                'sort' => 20,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kk',
                'title' => 'Бейне',
                'url' => 'beyne',
                'short' => 'Кәсіби бокс туралы бейне-Жекпе-жек, сұхбат және шолулар',
                'description' => 'Кәсіби бокс туралы үздік бейнематериалдарды қараңыз: жекпе-жек жазбалары, қазақстандық және әлемдік боксшылармен сұхбаттар, талдамалық шолулар және эксклюзивті репортаждар. Сақинадағы барлық оқиғалардан хабардар болыңыз',
                'views' => '0',
                'meta_title' => 'Кәсіби бокс туралы бейне-Жекпе-жек, сұхбат және шолулар',
                'meta_keywords' => 'бейне бокс, кәсіби бокс видео, боксшылардың жекпе-жегі, боксшылардың сұхбаты, жекпе-жекке шолу, қазақстандық бокс, әлемдік бокс оқиғалары',
                'meta_desc' => 'Кәсіби бокс туралы үздік бейнематериалдарды қараңыз: жекпе-жек жазбалары, қазақстандық және әлемдік боксшылармен сұхбаттар, талдамалық шолулар және эксклюзивті репортаждар. Сақинадағы барлық оқиғалардан хабардар болыңыз',
            ],
            [
                'sort' => 21,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'News',
                'url' => 'news',
                'short' => 'Professional Boxing News',
                'description' => 'Latest professional boxing news: current events, interviews, analytics, and fight results. Follow the latest trends in the world of boxing',
                'views' => '0',
                'meta_title' => 'Professional Boxing News',
                'meta_keywords' => 'boxing, professional boxing, boxing news, interviews with boxers, fight analysis, fight results, Kazakhstani boxing, world boxing events',
                'meta_desc' => 'Latest professional boxing news: current events, interviews, analytics, and fight results. Follow the latest trends in the world of boxing',
            ],
            [
                'sort' => 22,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Schedule',
                'url' => 'schedule',
                'short' => 'Ratings of boxers by weight categories',
                'description' => 'Current ratings of professional boxers by weight categories: follow the positions of Kazakhstani and world athletes, updates and analytics',
                'views' => '0',
                'meta_title' => 'Ratings of boxers by weight categories',
                'meta_keywords' => 'boxing ratings, professional boxing, boxer ratings, weight categories, Kazakhstani boxing, world boxing ratings, P4P',
                'meta_desc' => 'Current ratings of professional boxers by weight categories: follow the positions of Kazakhstani and world athletes, updates and analytics',
            ],
            [
                'sort' => 23,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Interview',
                'url' => 'interview',
                'short' => 'Interviews with professional boxers',
                'description' => 'Exclusive interviews with Kazakhstani and international professional boxers: opinions, strategies, preparation for fights and personal stories. Find out more',
                'views' => '0',
                'meta_title' => 'Interviews with professional boxers',
                'meta_keywords' => 'interviews of boxers, professional boxing, Kazakhstani boxers, world boxers, opinions of athletes, preparation for fights, personal stories of boxers',
                'meta_desc' => 'Exclusive interviews with Kazakhstani and international professional boxers: opinions, strategies, preparation for fights and personal stories. Find out more',
            ],
            [
                'sort' => 24,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Reviews',
                'url' => 'reviews',
                'short' => 'Boxing Forecasts and Reviews — Fight Analytics',
                'description' => 'Current forecasts and analytical reviews of professional boxing matches. Evaluation of upcoming fights, analysis of tactics, expert opinions and details about Kazakhstani and world boxers',
                'views' => '0',
                'meta_title' => 'Boxing Forecasts and Reviews — Fight Analytics',
                'meta_keywords' => 'fight forecasts, boxing reviews, boxing analytics, professional boxing, Kazakhstani boxing, world boxing events, fighting tactics',
                'meta_desc' => 'Current forecasts and analytical reviews of professional boxing matches. Evaluation of upcoming fights, analysis of tactics, expert opinions and details about Kazakhstani and world boxers',
            ],
            [
                'sort' => 25,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Results',
                'url' => 'results',
                'short' => 'The results of professional boxing fights',
                'description' => 'Current results of completed boxing matches: wins, losses, knockouts and refereeing decisions. Follow the results of the fights of Kazakhstani and world boxers',
                'views' => '0',
                'meta_title' => 'The results of professional boxing fights',
                'meta_keywords' => 'results of fights, professional boxing, results of fights, knockouts, refereeing decisions, Kazakhstani boxing, world boxing results',
                'meta_desc' => 'Current results of completed boxing matches: wins, losses, knockouts and refereeing decisions. Follow the results of the fights of Kazakhstani and world boxers',
            ],
            [
                'sort' => 26,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Open Ring',
                'url' => 'open-ring-en',
                'short' => 'Open Ring — Opinions and discussions about boxing',
                'description' => 'The Open Ring section is a platform for discussing current topics in the world of professional boxing. Read expert opinions, share your views and participate in discussions about Kazakhstani and world boxing.',
                'views' => '0',
                'meta_title' => 'Open Ring — Opinions and discussions about boxing',
                'meta_keywords' => 'open ring, boxing discussion, opinions about boxing, boxing discussions, professional boxing, kazakhstani boxing, world boxing events',
                'meta_desc' => 'The Open Ring section is a platform for discussing current topics in the world of professional boxing. Read expert opinions, share your views and participate in discussions about Kazakhstani and world boxing.',
            ],
            [
                'sort' => 27,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'WBSS',
                'url' => 'wbss-en',
                'short' => 'World Boxing Super Series (WBSS) — Tournament News and Reviews',
                'description' => 'Follow the latest news, results and analysis of the World Boxing Super Series (WBSS) tournament. Find out about the winners, participants and key points of the tournament, including the winners of the Muhammad Ali Trophy.',
                'views' => '0',
                'meta_title' => 'World Boxing Super Series (WBSS) — Tournament News and Reviews',
                'meta_keywords' => 'WBSS, World Boxing Super Series, трофей Мухаммеда Али, результаты WBSS, участники WBSS, профессиональный бокс, турниры по боксу',
                'meta_desc' => 'Follow the latest news, results and analysis of the World Boxing Super Series (WBSS) tournament. Find out about the winners, participants and key points of the tournament, including the winners of the Muhammad Ali Trophy.',
            ],
            [
                'sort' => 28,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'The rating is R4P',
                'url' => 'rating-r4r',
                'short' => 'Rating of the best boxers regardless of weight category (R4R)',
                'description' => 'The current rating of the best professional boxers, regardless of weight category (R4R). Follow the positions of Kazakhstani and international ring stars, updates and analytics',
                'views' => '0',
                'meta_title' => 'Rating of the best boxers regardless of weight category (R4R)',
                'meta_keywords' => 'R4R, rating of boxers, the best boxers in the world, pound for pound, professional boxing, Kazakhstani boxing, world boxing ratings',
                'meta_desc' => 'The current rating of the best professional boxers, regardless of weight category (R4R). Follow the positions of Kazakhstani and international ring stars, updates and analytics',
            ],
            [
                'sort' => 29,
                'activity' => 0,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'DIAMONDRING News',
                'url' => 'diamondring-news',
                'short' => 'DIAMONDRING News',
                'description' => 'DIAMONDRING News',
                'views' => '0',
                'meta_title' => 'DIAMONDRING News',
                'meta_keywords' => 'News, DIAMONDRING',
                'meta_desc' => 'DIAMONDRING News',
            ],
            [
                'sort' => 30,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Video',
                'url' => 'video-en',
                'short' => 'Professional Boxing Videos — Fights, interviews and reviews',
                'description' => 'Watch the best videos about professional boxing: recordings of fights, interviews with Kazakhstani and world boxers, analytical reviews and exclusive reports. Keep up to date with all the events of the ring',
                'views' => '0',
                'meta_title' => 'Professional Boxing Videos — Fights, interviews and reviews',
                'meta_keywords' => 'boxing videos, professional boxing videos, boxer fights, boxer interviews, fight reviews, kazakhstani boxing, world boxing events',
                'meta_desc' => 'Watch the best videos about professional boxing: recordings of fights, interviews with Kazakhstani and world boxers, analytical reviews and exclusive reports. Keep up to date with all the events of the ring',
            ],
        ];

        foreach ($rubrics as $rubric) {
            Rubric::create($rubric);
        }
    }
}
