<?php

namespace Database\Seeders;

use App\Models\Admin\Rubric\Rubric;
use Illuminate\Database\Seeder;

class RubricSeeder extends Seeder
{
    /**
     * Запуск сидера.
     */
    public function run(): void
    {
        $defaultIcon = '<svg class="w-4 h-4 fill-current text-slate-400 shrink-0 mr-3" viewBox="0 0 16 16"><path d="M15 15V5l-5-5H2c-.6 0-1 .4-1 1v14c0 .6 0 1 1 1h12c.6 0 1-.4 1-1zM3 2h6v4h4v8H3V2z"></path></svg>';

        $rubrics = [
            [
                'sort' => 1,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'News',
                'url' => 'news',
                'short' => 'Latest news',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'News - Latest Updates',
                'meta_keywords' => 'news, updates, latest',
                'meta_desc' => 'Stay updated with the latest news and updates.',
            ],
            [
                'sort' => 2,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Новости',
                'url' => 'novosti',
                'short' => 'Свежие новости',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Новости - Последние события',
                'meta_keywords' => 'новости, события, актуальное',
                'meta_desc' => 'Будьте в курсе последних новостей и событий.',
            ],
            [
                'sort' => 3,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'Жаңалықтар',
                'url' => 'zhanalyktar',
                'short' => 'Жаңа жаңалықтар',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Жаңалықтар - Соңғы оқиғалар',
                'meta_keywords' => 'жаңалықтар, оқиғалар, жаңа',
                'meta_desc' => 'Соңғы жаңалықтар мен оқиғалардан хабардар болыңыз.',
            ],
            [
                'sort' => 4,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Schedule',
                'url' => 'schedule',
                'short' => 'Upcoming events',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Event Schedule',
                'meta_keywords' => 'schedule, events, calendar',
                'meta_desc' => 'Stay informed about upcoming events.',
            ],
            [
                'sort' => 5,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Расписание',
                'url' => 'raspisanie',
                'short' => 'Ближайшие события',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'События и расписание',
                'meta_keywords' => 'расписание, события, календарь',
                'meta_desc' => 'Будьте в курсе ближайших событий.',
            ],
            [
                'sort' => 6,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'Кесте',
                'url' => 'keste',
                'short' => 'Алдағы оқиғалар',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Іс-шаралар кестесі',
                'meta_keywords' => 'кесте, оқиғалар, күнтізбе',
                'meta_desc' => 'Алдағы оқиғалардан хабардар болыңыз.',
            ],
            [
                'sort' => 7,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Interview',
                'url' => 'interview',
                'short' => 'Talks with experts',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Expert Interviews',
                'meta_keywords' => 'interview, experts, talks',
                'meta_desc' => 'Get insights from expert interviews.',
            ],
            [
                'sort' => 8,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Интервью',
                'url' => 'intervyu',
                'short' => 'Беседы с экспертами',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Интервью с экспертами',
                'meta_keywords' => 'интервью, эксперты, беседы',
                'meta_desc' => 'Получайте полезные советы от экспертов.',
            ],
            [
                'sort' => 9,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'Сұхбат',
                'url' => 'suhbat',
                'short' => 'Мамандармен сұхбаттар',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Мамандармен сұхбаттар',
                'meta_keywords' => 'сұхбат, мамандар, кеңестер',
                'meta_desc' => 'Мамандардан соңғы сұхбаттар мен кеңестер алыңыз.',
            ],
            [
                'sort' => 10,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Reviews',
                'url' => 'reviews',
                'short' => 'Market insights',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Business Reviews',
                'meta_keywords' => 'reviews, market, finance',
                'meta_desc' => 'Stay informed with the latest business reviews.',
            ],
            [
                'sort' => 11,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Обзоры',
                'url' => 'obzory',
                'short' => 'Обзор рынка',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Обзоры и финансы',
                'meta_keywords' => 'обзоры, рынок, финансы',
                'meta_desc' => 'Будьте в курсе последних бизнес-обзоров.',
            ],
            [
                'sort' => 12,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'Шолулар',
                'url' => 'sholular',
                'short' => 'Нарық шолуы',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Бизнес шолулары',
                'meta_keywords' => 'шолулар, нарық, қаржы',
                'meta_desc' => 'Соңғы бизнес шолуларын алыңыз.',
            ],
            [
                'sort' => 13,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Results',
                'url' => 'results',
                'short' => 'Travel tips',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Travel Results',
                'meta_keywords' => 'results, travel, guides',
                'meta_desc' => 'Discover new destinations with our travel results.',
            ],
            [
                'sort' => 14,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Результаты',
                'url' => 'rezultaty',
                'short' => 'Советы для путешествий',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Результаты и туризм',
                'meta_keywords' => 'результаты, туризм, советы',
                'meta_desc' => 'Откройте для себя новые места с нашими результатами.',
            ],
            [
                'sort' => 15,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'Нәтижелер',
                'url' => 'natizheler',
                'short' => 'Саяхат кеңестері',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Саяхат нәтижелері',
                'meta_keywords' => 'нәтижелер, саяхат, гидтер',
                'meta_desc' => 'Біздің саяхат нәтижелерімізбен жаңа бағыттарды ашыңыз.',
            ],
            [
                'sort' => 16,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'Open Ring',
                'url' => 'open-ring',
                'short' => 'Learning resources',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Open Ring Resources',
                'meta_keywords' => 'open ring, learning, courses',
                'meta_desc' => 'Find the best resources for open ring and growth.',
            ],
            [
                'sort' => 17,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Open Ring ru',
                'url' => 'open-ring-ru',
                'short' => 'Ресурсы для обучения',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Ресурсы Open Ring',
                'meta_keywords' => 'open ring, обучение, курсы',
                'meta_desc' => 'Найдите лучшие ресурсы для обучения и развития в Open Ring.',
            ],
            [
                'sort' => 18,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'Open Ring kz',
                'url' => 'open-ring-kz',
                'short' => 'Оқу ресурстары',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Open Ring оқу ресурстары',
                'meta_keywords' => 'open ring, оқу, курстар',
                'meta_desc' => 'Open Ring үшін үздік оқу ресурстарын табыңыз.',
            ],
            [
                'sort' => 19,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'WBSS',
                'url' => 'wbss',
                'short' => 'World Boxing Super Series',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'WBSS News',
                'meta_keywords' => 'wbss, boxing, super series',
                'meta_desc' => 'Stay updated with the latest from WBSS.',
            ],
            [
                'sort' => 20,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'WBSS ru',
                'url' => 'wbss-ru',
                'short' => 'Всемирная бокс-суперсерия',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Новости WBSS',
                'meta_keywords' => 'wbss, бокс, суперсерия',
                'meta_desc' => 'Будьте в курсе последних новостей WBSS.',
            ],
            [
                'sort' => 21,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'WBSS kz',
                'url' => 'wbss-kz',
                'short' => 'Әлемдік бокс суперсериясы',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'WBSS жаңалықтары',
                'meta_keywords' => 'wbss, бокс, суперсерия',
                'meta_desc' => 'WBSS соңғы жаңалықтарымен танысыңыз.',
            ],
            [
                'sort' => 22,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'en',
                'title' => 'P4P Rating',
                'url' => 'p4p-rating',
                'short' => 'Top pound-for-pound fighters',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'P4P Fighters Rating',
                'meta_keywords' => 'p4p, boxing, fighters',
                'meta_desc' => 'Check out the latest P4P boxing ratings.',
            ],
            [
                'sort' => 23,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'ru',
                'title' => 'Рейтинг Р4Р',
                'url' => 'reyting-p4p',
                'short' => 'Лучшие бойцы вне весовых категорий',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'Рейтинг боксёров P4P',
                'meta_keywords' => 'p4p, бокс, бойцы',
                'meta_desc' => 'Ознакомьтесь с последними рейтингами боксёров P4P.',
            ],
            [
                'sort' => 24,
                'activity' => 1,
                'icon' => $defaultIcon,
                'locale' => 'kz',
                'title' => 'P4P рейтингі',
                'url' => 'p4p-reytingi',
                'short' => 'Салмақ дәрежесіне қарамастан үздік жекпе-жекшілер',
                'description' => 'Описание',
                'views' => '0',
                'meta_title' => 'P4P боксерлер рейтингі',
                'meta_keywords' => 'p4p, бокс, жекпе-жекшілер',
                'meta_desc' => 'P4P боксерлердің соңғы рейтингімен танысыңыз.',
            ],
        ];

        foreach ($rubrics as $rubric) {
            Rubric::create($rubric);
        }
    }
}
