<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'type' => 'static',
                'option' => 'infoModVersion',
                'value' => '1.0.0',
                'constant' => 'INFO_MOD_VERSION',
                'category' => 'system',
                'description' => 'Версия движка сайта',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'siteLayout',
                'value' => 'Default',
                'constant' => 'SITE_LAYOUT',
                'category' => 'public',
                'description' => 'Шаблон публичной части сайта',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'checkbox',
                'option' => 'downtimeSite',
                'value' => 'false',
                'constant' => 'DOWNTIME_SITE',
                'category' => 'public',
                'description' => 'Включение/Выключение публичной части сайта на технические работы',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'widgetHexColor',
                'value' => '155e75',
                'constant' => 'WIDGET_HEX_COLOR',
                'category' => 'admin',
                'description' => 'Задаёт цвет панелей сайдбара и виджетов',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'float',
                'option' => 'widgetOpacity',
                'value' => '0.99',
                'constant' => 'WIDGET_OPACITY',
                'category' => 'admin',
                'description' => 'Задаёт прозрачность цвета панелей сайдбара и виджетов',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRubrics',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_RUBRICS',
                'category' => 'admin',
                'description' => 'Показывать количество Рубрик в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRubrics',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_RUBRICS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Рубрик по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountSections',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_SECTIONS',
                'category' => 'admin',
                'description' => 'Показывать количество Секций в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortSections',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_SECTIONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Секций по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountArticles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ARTICLES',
                'category' => 'admin',
                'description' => 'Показывать количество Постов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortArticles',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_ARTICLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Постов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountTags',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_TAGS',
                'category' => 'admin',
                'description' => 'Показывать количество Тегов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortTags',
                'value' => 'name',
                'constant' => 'ADMIN_SORT_TAGS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Тегов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountComments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_COMMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество Комментариев в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortComments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_COMMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Комментариев по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountBanners',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_BANNERS',
                'category' => 'admin',
                'description' => 'Показывать количество Баннеров в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortBanners',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_BANNERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Баннеров по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountVideos',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_VIDEOS',
                'category' => 'admin',
                'description' => 'Показывать количество Видео в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortVideos',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_VIDEOS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Видео по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountUsers',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_USERS',
                'category' => 'admin',
                'description' => 'Показывать количество Пользователей в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortUsers',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_USERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Пользователей по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRoles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ROLES',
                'category' => 'admin',
                'description' => 'Показывать количество Релей в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRoles',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ROLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Релей по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountPermissions',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_PERMISSIONS',
                'category' => 'admin',
                'description' => 'Показывать количество Разрешений в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortPermissions',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_PERMISSIONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Разрешений по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountPlugins',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_PLUGINS',
                'category' => 'admin',
                'description' => 'Показывать количество Модулей в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortPlugins',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_PLUGINS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Модулей по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountCategories',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_CATEGORIES',
                'category' => 'admin',
                'description' => 'Показывать количество Категорий в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortCategories',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_CATEGORIES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Категорий по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountAthletes',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ATHLETES',
                'category' => 'admin',
                'description' => 'Показывать количество Атлетов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortAthletes',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ATHLETES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Атлетов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountTournaments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_TOURNAMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество Турниров в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortTournaments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_TOURNAMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Турниров по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountSettings',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_SETTINGS',
                'category' => 'admin',
                'description' => 'Показывать количество Параметров в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortSettings',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_SETTINGS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Параметров по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicLightBackgroundColor',
                'value' => 'bg-amber-50',
                'constant' => 'PUBLIC_LIGHT_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS фонового цвета светлого режима',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicDarkBackgroundColor',
                'value' => 'bg-blue-800',
                'constant' => 'PUBLIC_DARK_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS фонового цвета тёмного режима',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicHeaderLightBackgroundColor',
                'value' => 'bg-slate-100',
                'constant' => 'PUBLIC_HEADER_LIGHT_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS цвета светлого режима для header',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicHeaderDarkBackgroundColor',
                'value' => 'bg-slate-800',
                'constant' => 'PUBLIC_HEADER_DARK_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS цвета тёмного режима для header',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'checkbox',
                'option' => 'ViewLeftColumn',
                'value' => 'true',
                'constant' => 'VIEW_LEFT_COLUMN',
                'category' => 'public',
                'description' => 'Включение/Выключение левой колонки в публичной части',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'checkbox',
                'option' => 'ViewRightColumn',
                'value' => 'true',
                'constant' => 'VIEW_RIGHT_COLUMN',
                'category' => 'public',
                'description' => 'Включение/Выключение правой колонки в публичной части',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicViewArticle',
                'value' => 'grid',
                'constant' => 'PUBLIC_VIEW_ARTICLE',
                'category' => 'public',
                'description' => 'Вид показа блоков Статей в секциях grid/horizontal',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'PublicCountArticle',
                'value' => '3',
                'constant' => 'PUBLIC_COUNT_ARTICLE',
                'category' => 'public',
                'description' => 'Показывать количество Статей в секциях по умолчанию',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkColor',
                'value' => 'bg-gray-700',
                'constant' => 'ADMIN_SIDEBAR_DARK_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS цвета тёмного режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightColor',
                'value' => 'bg-cyan-800',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS цвета светлого режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkText',
                'value' => 'text-slate-200',
                'constant' => 'ADMIN_SIDEBAR_DARK_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета текста тёмного режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightText',
                'value' => 'text-slate-200',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета текста светлого режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkHoverText',
                'value' => 'text-red-300',
                'constant' => 'ADMIN_SIDEBAR_DARK_HOVER_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета при наведении на текст в тёмном режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightHoverText',
                'value' => 'text-red-300',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_HOVER_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета при наведении на текст в светлом режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkActiveText',
                'value' => 'text-yellow-200',
                'constant' => 'ADMIN_SIDEBAR_DARK_ACTIVE_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета активной ссылки в тёмном режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightActiveText',
                'value' => 'text-yellow-200',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_ACTIVE_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета активной ссылки в светлом режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],

            // Добавьте остальные параметры
        ];

        DB::table('settings')->insert($settings);
    }
}
