<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'type' => 'static',
                'option' => 'infoModVersion',
                'value' => '1.0.0',
                'constant' => 'INFO_MOD_VERSION',
                'category' => 'system',
                'description' => 'Версия движка сайта',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'siteLayout',
                'value' => 'Default',
                'constant' => 'SITE_LAYOUT',
                'category' => 'public',
                'description' => 'Шаблон публичной части сайта',
                'activity' => true,
            ],
            [
                'type' => 'checkbox',
                'option' => 'downtimeSite',
                'value' => 'false',
                'constant' => 'DOWNTIME_SITE',
                'category' => 'public',
                'description' => 'Включение/Выключение публичной части сайта на технические работы',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'widgetHexColor',
                'value' => '155e75',
                'constant' => 'WIDGET_HEX_COLOR',
                'category' => 'admin',
                'description' => 'Задаёт цвет панелей сайдбара и виджетов',
                'activity' => true,
            ],
            [
                'type' => 'float',
                'option' => 'widgetOpacity',
                'value' => '0.99',
                'constant' => 'WIDGET_OPACITY',
                'category' => 'admin',
                'description' => 'Задаёт прозрачность цвета панелей сайдбара и виджетов',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'locale',
                'value' => 'ru',
                'constant' => 'LOCALE',
                'category' => 'system',
                'description' => 'переключение локальных языков',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRubrics',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_RUBRICS',
                'category' => 'admin',
                'description' => 'Показывать количество Рубрик в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRubrics',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_RUBRICS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Рубрик по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountSections',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_SECTIONS',
                'category' => 'admin',
                'description' => 'Показывать количество Секций в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortSections',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_SECTIONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Секций по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountArticles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ARTICLES',
                'category' => 'admin',
                'description' => 'Показывать количество Постов в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortArticles',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_ARTICLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Постов по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountTags',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_TAGS',
                'category' => 'admin',
                'description' => 'Показывать количество Тегов в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortTags',
                'value' => 'name',
                'constant' => 'ADMIN_SORT_TAGS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Тегов по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountComments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_COMMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество Комментариев в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortComments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_COMMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Комментариев по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountBanners',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_BANNERS',
                'category' => 'admin',
                'description' => 'Показывать количество Баннеров в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortBanners',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_BANNERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Баннеров по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountUsers',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_USERS',
                'category' => 'admin',
                'description' => 'Показывать количество Пользователей в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortUsers',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_USERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Пользователей по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRoles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ROLES',
                'category' => 'admin',
                'description' => 'Показывать количество Релей в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRoles',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ROLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Релей по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRoles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ROLES',
                'category' => 'admin',
                'description' => 'Показывать количество Релей в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRoles',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ROLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Релей по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountPermissions',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_PERMISSIONS',
                'category' => 'admin',
                'description' => 'Показывать количество Разрешений в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortPermissions',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_PERMISSIONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Разрешений по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountParameters',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_PARAMETERS',
                'category' => 'admin',
                'description' => 'Показывать количество Параметров в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortParameters',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_PARAMETERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Параметров по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountPlugins',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_PLUGINS',
                'category' => 'admin',
                'description' => 'Показывать количество Модулей в таблице Панели Администратора',
                'activity' => true,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortPlugins',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_PLUGINS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Модулей по умолчанию в таблице Панели Администратора',
                'activity' => true,
            ],
            // Добавьте остальные параметры
        ];

        DB::table('settings')->insert($settings);
    }
}
